CREATE TABLE BERKAS (
IDBerkas INT not null,
IdMKS INT not null,
Nama VARCHAR(100) NOT NULL,
Alamat VARCHAR(100) NOT NULL,
PRIMARY KEY(IDBerkas,IdMKS),
FOREIGN KEY(IdMKS) REFERENCES MATA_KULIAH_SPESIAL(IDMKS) ON DELETE CASCADE ON UPDATE CASCADE
);