CREATE TABLE JADWAL_SIDANG (
IDJadwal INT NOT NULL,
IdMKS INT NOT NULL,
Tanggal DATE NOT NULL,
JamMulai TIME NOT NULL,
JamSelesai TIME NOT NULL,
IdRuangan INT NOT NULL,
PRIMARY KEY(IDJadwal, IdMKS),
FOREIGN KEY(IdMKS) REFERENCES MATA_KULIAH_SPESIAL(IDMKS) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(IdRuangan) REFERENCES RUANGAN(IdRuangan) ON DELETE CASCADE ON UPDATE CASCADE
);