CREATE TABLE DOSEN_PEMBIMBING(
	IdMKS INT NOT NULL,
	NIPDosen varchar(10) NOT NULL,
PRIMARY KEY(IdMKS, NIPDosen),
FOREIGN KEY(IdMKS) REFERENCES MATA_KULIAH_SPESIAL(IdMKS) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(NIPdosen) REFERENCES DOSEN(nip) ON DELETE CASCADE ON UPDATE CASCADE
);