CREATE TABLE DOSEN_PENGUJI(
IdMKS INT NOT NULL ,
	NIPDosen varchar(10) NOT NULL,
	PRIMARY KEY(IdMKS, NIPDosen),
FOREIGN KEY(IdMKS) REFERENCES MATA_KULIAH_SPESIAL(IDMKS) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(NIPdosen) REFERENCES DOSEN(NIP) ON DELETE CASCADE ON UPDATE CASCADE
	);