insert into sisidang.dosen (NIP, Nama, Username, Password, Email, Institusi) values
('1','Barry Nuridan','barry.nuridan','barrynur','barrynuridan@gmail.com','UI'),
('2','Nadya Putri','nadya.putri','nadyapp','nadyaputri@gmail.com','UI'),
('3','Rommy Rafael','rommy.rafael','1rommy1','rommyrafael@gmail.com','UI'),
('4','Tantjana Saphira','t.saphira','tsaphira22','t.saphira@gmail.com','UI'),
('5','Randy Roji','randy.roji','rojiroji','randyroji@gmail.com','UI'),
('6','Mega Mentari','mega.mentari','mahatarimega','mentarimega@gmail.com','UI'),
('7','Lintang Dari','lintang.dari','lingtangtangtang','lintang.d12@gmail.com','UI'),
('8','Gemilang Pradimo','gemilang.pradimo','gemigemilang','gemilangprad@gmail.com','UI'),
('9','Bramatio Kapa','bramantio.kapa','kapakapa','bram.kapa@gmail.com','UI'),
('10','Kanya Rai','kanya.rai','krai2340','kanyarai@gmail.com','UI'),
('11','Luwidita Putri','luwidita.putri','luwiditabnmq','luwiditap@gmail.com','UI'),
('12','Raka Bohemi','raka.bohemi','bohemianrhapsody','bohemian@gmail.com','UI'),
('13','Putra Gemilang','putra.gemilang','putraa123g','p.gemilang@gmail.com','UI'),
('14','Lia Matari','lia.matari','matari098','liamatari@gmail.com','UI'),
('15','Masayu Rania','masayu.rania','raniasasa','masayu.rania@gmail.com','UI'),
('16','Luky Lobe','luki.lobe','luckyomg','lukylukyluky@gmail.com','UI'),
('17','Rahadian ','rahadian','rahadian7878','rahadianr@gmail.com','UI'),
('18','Damar Darin','damar.darin','damardarinnn','damardarin@gmail.com','UI'),
('19','Lia Benita','lia.benita','benitabeni','benita.lia@gmail.com','UI'),
('20','Rama Sadikin','rama.sadikin','sadikin23rama','rama.sadikin@gmail.com','UI'),
('21','Julia','jking0','fITB4WxG0Yd','jhansen0@tiny.cc','UI'),
('22','Kimberly','kparker1','OVm6KJlWBND3','kgarza1@wikispaces.com','UI'),
('23','Denise','dmcdonald2','9KeW7exmP','djohnson2@usatoday.com','UI'),
('24','Betty','bward3','uhFgNa9j','bphillips3@elpais.com','UI'),
('25','Katherine','kwashington4','NPnU2eX','kkennedy4@123-reg.co.uk','UI'),
('26','John','jyoung5','HODWic1B1z','jhill5@dropbox.com','UI'),
('27','Sean','sgeorge6','2dTKhZrdrc','sperry6@amazon.co.jp','UI'),
('28','Angela','aflores7','AMoWJ0s','aandrews7@theguardian.com','UI'),
('29','Christopher','cpierce8','PMl9zMVZ','cyoung8@disqus.com','UI'),
('30','Eugene','ethomas9','nza83YKqNUus','eaustin9@mozilla.com','UI'),
('31','Wayne','wreynoldsa','ERzZos3y','wbaileya@yolasite.com','UI'),
('32','Kathleen','kgrayb','R62cholnSwW1','kwoodsb@sciencedirect.com','UI'),
('33','Howard','hwestc','3rGlQ5JWXD','hrichardsonc@bbb.org','UI'),
('34','Walter','wmarshalld','AoIlXbNdCJXC','wbryantd@odnoklassniki.ru','UI'),
('35','Sharon','spalmere','WKuaDf','smeyere@hibu.com','UI'),
('36','Alan','aburnsf','JZy0cek','amitchellf@blogs.com','UI'),
('37','Janet','jlawsong','CeipemEDPJnm','jhowellg@youtube.com','UI'),
('38','Todd','thudsonh','uRrFIm2h','tfreemanh@oracle.com','UI'),
('39','Ryan','rharperi','P4wyZHOL','rlittlei@github.io','UI'),
('40','Clarence','creedj','0Eq5m1L86eW','cperezj@hugedomains.com','UI'),
('41','Gloria','gmorrisonk','lzrMGg','gblackk@admin.ch','UI'),
('42','Helen','hcolemanl','mvoz0t6ph','hallenl@adobe.com','UI'),
('43','Samuel','sfisherm','UTWmDi1zSMFD','shuntm@baidu.com','UI'),
('44','Julia','jhalln','nMV7q2wIlN','jbarnesn@mediafire.com','UI'),
('45','Lisa','lgreeno','dAgM352dyQ','lrobertso@behance.net','UI'),
('46','Jeremy','jmillerp','HFMExOnX5','jellisp@nyu.edu','UI'),
('47','Gary','gboydq','9MeC5r','gbutlerq@webmd.com','UI'),
('48','Craig','cdixonr','xjvMpBRtdNjB','crossr@odnoklassniki.ru','UI'),
('49','Denise','djamess','Lu9UJXjxJbV','dgilberts@nbcnews.com','UI'),
('50','Louise','ldayt','5lSBuL8SCE','lwoodt@samsung.com','UI');